client:
  - src/client/**/*
server:
  - src/server/**/*
pages:
  - src/pages/**/*
scripts:
  - scripts/**/*
browser-automation:
  - browser-automation/**/*
test:
  - test/**/*
public:
  - public/**/*
readme:
  - README.md
dependencies:
  - any: ['package.json', 'package-lock.json', 'yarn.lock']