language: node_js
node_js: 
  - 14.7.0
  - 12.18.3

cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run express --touch
  - yarn run koa --touch
  - yarn run hapi --touch
  - yarn run be

notifications:
  email:
    recipients:
      - eric14706@gmail.com
    on_success: never
    on_failure: always
# use vercel for deployment